### ISSUE TITLE
Build failed: Build input file cannot be found: TreeSitterObjC.o

### ISSUE THREAD

**Issue by krystiankolodziej** [davidbalbert/Watt#131]
I am trying to compile the **Watt** target (from the main branch) but I am getting an error:

![Zrzut ekranu 2024-11-23 o 14 33 29](https://github.com/user-attachments/assets/bc21ed9a-70e0-42da-89de-781d5fc7a916)

**Comment by davidbalbert** [comment]
Looks like you figured it out? LMK if you run into any other issues. 

For anyone else reading this, my guess is they probably forgot to clone the submodules.

**Comment by krystiankolodziej** [comment]
You are right, the submodule was not pulled. I used SourceTree with the "Recurse submodules" option, but it did not work.
The project compiles correctly, but unfortunately, assertions sometimes occur during execution.

**Comment by davidbalbert** [comment]
@krystiankolodziej yeah, it's definitely not ready for production. If you can reproduce any of the assertions, and you'd be willing, please file a bug!
